### PR TITLE
Ep sessionstorage

### PR DESCRIPTION
**Pull request by erinepolley**
# Description

I set up the initial js file structures, as well as the initial session storage method in main.js (commented out). 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Testing Instructions

Please look at the file structure and make sure that 1) everything is spelled correctly, and 2) all files are present in every folder. 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by erinepolley** [comment]
`git fetch --all`
`git checkout ep-sessionstorage`

**Review by bitomann — APPROVED** [review]
Looks good

**Review by MatthewScott32 — APPROVED** [review]
khaley khoob

**Review by schatfield — APPROVED** [review]
is awesome thank you

**Pull request merged**
